SELECT T.ID_TRABALHO AS Trabalho,
       AVL.NOMEALUNO AS Nome,
       AVL.NOTA_AVALIACAO AS Nota
       FROM TRABALHO T
       INNER JOIN AVALIACAO_ALUNO AVL 
       ON T.ID_TRABALHO = AVL.ID_TRABALHO
       ORDER BY Trabalho 
