
    ALTER TABLE LABDATABASE.AVALIACAO_ALUNO DROP CONSTRAINT ALUNO_AVALIACAO_ALUNO_FK;
    ALTER TABLE LABDATABASE.AVALIACAO_ALUNO DROP CONSTRAINT PROVA_AVALIACAO_ALUNO_FK;
    ALTER TABLE LABDATABASE.AVALIACAO_ALUNO DROP CONSTRAINT TRABALHO_AVALIACAO_ALUNO_FK;

    DROP TABLE LABDATABASE.ALUNO;
    DROP TABLE LABDATABASE.PROVA;
    DROP TABLE LABDATABASE.TRABALHO;
    DROP TABLE LABDATABASE.AVALIACAO_ALUNO;

    DROP SEQUENCE LABDATABASE.ALUNO_ID_ALUNO_SEQ;
    DROP SEQUENCE LABDATABASE.PROVA_ID_PROVA_SEQ;
    DROP SEQUENCE LABDATABASE.TRABALHO_ID_TRABALHO_SEQ;
    DROP SEQUENCE LABDATABASE.AVALIACAO_ALUNO_ID_AVALIACAO_ALUNO_SEQ;

    CREATE TABLE LABDATABASE.ALUNO (
        ID_ALUNO NUMBER NOT NULL,
        NOME VARCHAR2(255) NOT NULL,
        IDADE NUMBER NOT NULL,
        TURMA VARCHAR2(40) NOT NULL,
        CONSTRAINT ALUNO_PK PRIMARY KEY (ID_ALUNO)
    );

    CREATE TABLE LABDATABASE.PROVA (
        ID_PROVA NUMBER NOT NULL,
        QUANT_QUESTAO NUMBER NOT NULL,
        DATE_APLICACAO DATE NOT NULL,
        CONSTRAINT PROVA_PK PRIMARY KEY (ID_PROVA)
    );

    CREATE TABLE LABDATABASE.TRABALHO (
        ID_TRABALHO NUMBER NOT NULL,
        QTDCRITERIOSAVALIADOS NUMBER NOT NULL,
        DATE_ENTREGA DATE NOT NULL,
        CONSTRAINT TRABALHO_PK PRIMARY KEY (ID_TRABALHO)
    );

    CREATE TABLE LABDATABASE.AVALIACAO_ALUNO (
        ID_AVALIACAO_ALUNO NUMBER NOT NULL,
        ID_ALUNO NUMBER NOT NULL,
        ID_PROVA NUMBER NOT NULL,
        ID_TRABALHO NUMBER NOT NULL,
        NOTA_AVALIACAO NUMBER NOT NULL,
        NOMEALUNO VARCHAR2(200) NOT NULL,
        CONSTRAINT ID_AVALIACAO_ALUNO_PK PRIMARY KEY (ID_AVALIACAO_ALUNO)
    );

    CREATE SEQUENCE LABDATABASE.ALUNO_ID_ALUNO_SEQ;
    CREATE SEQUENCE LABDATABASE.PROVA_ID_PROVA_SEQ;
    CREATE SEQUENCE LABDATABASE.TRABALHO_ID_TRABALHO_SEQ;
    CREATE SEQUENCE LABDATABASE.AVALIACAO_ALUNO_ID_AVALIACAO_ALUNO_SEQ;

    ALTER TABLE LABDATABASE.AVALIACAO_ALUNO ADD CONSTRAINT ALUNO_AVALIACAO_ALUNO_FK
    FOREIGN KEY (ID_ALUNO)
    REFERENCES LABDATABASE.ALUNO (ID_ALUNO)
    NOT DEFERRABLE;

    ALTER TABLE LABDATABASE.AVALIACAO_ALUNO ADD CONSTRAINT PROVA_AVALIACAO_ALUNO_FK
    FOREIGN KEY (ID_PROVA)
    REFERENCES LABDATABASE.PROVA (ID_PROVA)
    NOT DEFERRABLE;

    ALTER TABLE LABDATABASE.AVALIACAO_ALUNO ADD CONSTRAINT TRABALHO_AVALIACAO_ALUNO_FK
    FOREIGN KEY (ID_TRABALHO)
    REFERENCES LABDATABASE.TRABALHO (ID_TRABALHO)
    NOT DEFERRABLE;

    GRANT ALL ON LABDATABASE.ALUNO TO LABDATABASE;
    GRANT ALL ON LABDATABASE.PROVA TO LABDATABASE;
    GRANT ALL ON LABDATABASE.TRABALHO TO LABDATABASE;
    GRANT ALL ON LABDATABASE.AVALIACAO_ALUNO TO LABDATABASE;

    ALTER USER LABDATABASE quota unlimited on USERS;
