/*INSERE DADOS NAS TABELAS*/

INSERT INTO LABDATABASE.ALUNO VALUES(ALUNO_ID_ALUNO_SEQ.NEXTVAL, 'Erick Gomes', 21, 'A');
INSERT INTO LABDATABASE.ALUNO VALUES(ALUNO_ID_ALUNO_SEQ.NEXTVAL, 'Henrique Alexandre', 23, 'B');
INSERT INTO LABDATABASE.ALUNO VALUES(ALUNO_ID_ALUNO_SEQ.NEXTVAL, 'Pedro Barros', 19, 'A');
INSERT INTO LABDATABASE.ALUNO VALUES(ALUNO_ID_ALUNO_SEQ.NEXTVAL, 'Pedro Guerra', 20, 'C');
INSERT INTO LABDATABASE.ALUNO VALUES(ALUNO_ID_ALUNO_SEQ.NEXTVAL, 'Matheus Peixoto', 20, 'B');

INSERT INTO LABDATABASE.PROVA VALUES(0, 10, '28 OCT 2023');
INSERT INTO LABDATABASE.PROVA VALUES(PROVA_ID_PROVA_SEQ.NEXTVAL, 10, '28 OCT 2023');
INSERT INTO LABDATABASE.PROVA VALUES(PROVA_ID_PROVA_SEQ.NEXTVAL, 8, '30 OCT 2023');

INSERT INTO LABDATABASE.TRABALHO VALUES(0, 5, '05 NOV 2023');
INSERT INTO LABDATABASE.TRABALHO VALUES(TRABALHO_ID_TRABALHO_SEQ.NEXTVAL, 5, '05 NOV 2023');
INSERT INTO LABDATABASE.TRABALHO VALUES(TRABALHO_ID_TRABALHO_SEQ.NEXTVAL, 3, '31 OCT 2023');
INSERT INTO LABDATABASE.TRABALHO VALUES(TRABALHO_ID_TRABALHO_SEQ.NEXTVAL, 4, '02 NOV 2023');

INSERT INTO LABDATABASE.AVALIACAO_ALUNO VALUES(AVALIACAO_ALUNO_ID_AVALIACAO_ALUNO_SEQ.NEXTVAL, 4, 0, 3, 8, 'Pedro Guerra');
INSERT INTO LABDATABASE.AVALIACAO_ALUNO VALUES(AVALIACAO_ALUNO_ID_AVALIACAO_ALUNO_SEQ.NEXTVAL, 2, 2, 0, 9, 'Henrique Alexandre');
INSERT INTO LABDATABASE.AVALIACAO_ALUNO VALUES(AVALIACAO_ALUNO_ID_AVALIACAO_ALUNO_SEQ.NEXTVAL, 3, 0, 3, 6, 'Pedro Barros');
INSERT INTO LABDATABASE.AVALIACAO_ALUNO VALUES(AVALIACAO_ALUNO_ID_AVALIACAO_ALUNO_SEQ.NEXTVAL, 5, 0, 1, 10, 'Matheus Peixoto');
INSERT INTO LABDATABASE.AVALIACAO_ALUNO VALUES(AVALIACAO_ALUNO_ID_AVALIACAO_ALUNO_SEQ.NEXTVAL, 1, 2, 0, 8, 'Erick Gomes');

COMMIT;